---
driver:
  name: vagrant

provisioner:
  product_name: chef
  product_version: latest

verifier:
  name: inspec
  inspec_tests:
    - test/integration/default

platforms:
  - name: ubuntu-16.04
    driver:
      network:
        - ["forwarded_port", {guest: 80, host: 8080}]

suites:
  - name: install-snipe-it
    run_list:
      - recipe[test::default]