---
driver:
  name: vagrant

provisioner:
  product_name: chef
  product_version: latest

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      network:
        - ["forwarded_port", {guest: 80, host: 8080}]

suites:
  - name: default
    run_list:
      - recipe[snipe-it::default]
    verifier:
      inspec_tests:
        - test/integration/default