---
driver:
  name: azurerm
  location: 'West US'
  machine_size: 'Standard_D3_v2'
  subscription_id: <%= ENV['AZURE_SUBSCRIPTION_ID'] %>
  vnet_id: /subscriptions/<%= ENV['AZURE_SUBSCRIPTION_ID'] %>/resourceGroups/<%= ENV['AZURE_ER_RESOURCE_GROUP'] %>/providers/Microsoft.Network/virtualNetworks/<%= ENV['AZURE_ER_VNET_NAME'] %>
  subnet_id: Subnet-1

provisioner:
  product_name: chef
  product_version: latest

verifier:
  name: inspec
  inspec_tests:
    - test/integration/default

platforms:
  - name: ubuntu-16.04
    driver:
      image_urn: Canonical:UbuntuServer:16.04-LTS:latest

suites:
  - name: snipe-it-test
    driver:
      vm_name: snipe-it-test
    run_list:
      - recipe[snipe-it::default]
    attributes:
      snipeit:
        database:
          domain: <%= ENV['MYSQL_SERVER_DOMAIN'] || '' %>
          hostname: <%= ENV['MYSQL_SERVER_HOSTNAME'] || 'localhost' %>
          username: <%= ENV['MYSQL_SERVER_USERNAME'] || 'bacon' %>
          password: <%= ENV['MYSQL_SERVER_PASSWORD'] || 'eggs' %>
        php:
          app_key: <%= ENV['APP_KEY'] || 'base64:superinsecurekey' %>
        smtp:
          host: <%= ENV['SMTP_HOSTNAME'] || 'localhost' %>
          mailbox: <%= ENV['SMTP_MAILBOX'] || 'mail@localhost' %>
          username: <%= ENV['SMTP_USERNAME'] || 'mail@localhost' %>
          password: <%= ENV['SMTP_PASSWORD'] || 'mymailpassword' %>